language: ruby
rvm:
  - 2.5.1
before_script:
  - curl -L -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -jxvf phantomjs-2.1.1-linux-x86_64.tar.bz2 phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  - sudo mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/
  - chmod 755 /usr/local/bin/phantomjs
  - rm phantomjs-2.1.1-linux-x86_64.tar.bz2 && rm -rf phantomjs-2.1.1-linux-x86_64/bin
  - gem install bundler-audit
script:
  - bundle exec rspec --format documentation
  - bundle exec rubocop --config .rubocop.yml
  - bundle-audit check --update
